name: Hugo Site CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  permissions:
    contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes as submodules
          fetch-depth: 0    # Fetch all history for all branches

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'extended'

      - name: Build Hugo Site
        run: |
          hugo --baseURL 'https://greencloud-tang.github.io/chinese-business-directory/'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true  # This is the key change!